version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: bias-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: bias-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:

networks:
  bias-backend: